### ISSUE TITLE
How to use pretrained checkpoints?

### ISSUE THREAD

**Issue by dzy1997** [antonilo/unsupervised_detection#1]
I am trying to use pretrained checkpoints (your model and PWCNet) specified in README.md to test on DAVIS2016. I am modifying file test_DAVIS2016_raw.sh
Your model checkpoint has 3 files under davis_best_model
- model.best.data-00000-of-00001
- model.best.index
- model.best.meta

PWCNet checkpoint has 4 files under the folder on google drive
- checkpoint
- pwcnet.ckpt-595000.data-00000-of-00001
- pwcnet.ckpt-595000.index
- pwcnet.ckpt-595000.meta

Which one should I specify for CKPT_FILE and PWC_CKPT_FILE?
Thank you!

**Comment by antonilo** [comment]
Hi @dzy1997! You should set the CKPT_FILE and PWC_CKPT_FILE to the pre-extension filenames. Example: CKPT_FILE=/path/to/model.best 

Hope this helps!
