### ISSUE TITLE
make_initializable_iterator exception

### ISSUE THREAD

**Issue by AwesomeLele** [antonilo/unsupervised_detection#14]
Hello,
I'm trying to run the test_DAVIS2016_raw script. When i execute it i get the following execption: 

`[AttributeError: 'PrefetchDataset' object has no attribute '_make_initializable_iterator'
`
raised in line 2733 of  /python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py" file. Has anyone had this issue?
I should note that i used tf_upgrade_v2 to update the project scripts to tensorfflow v2.

**Comment by eppoj** [comment]
I couldn't get it working with the tf_upgrade_v2 script either due the contrib modules that are used in the source code. I eventually rolled back to tensorflow 1.14.0 and cuda 10.0 there it works fine.

**Comment by AwesomeLele** [comment]
Yes, that's the problem, as matter of fact i'm trying to install tf 1.14 but got problems in pip3. You installed it using a link or something ?

**Comment by eppoj** [comment]
ehh I am not sure how I installed it I might can find it back in my terminal history. What platform are you trying to run the sofware on?

**Comment by AwesomeLele** [comment]
I'm using ubuntu 20.04 and python 3.8, i tried downgrading using the command: 
`pip3 install tensorflow == 1.14`
but it couldn't collect the version ( says it can collect only 2.* versions).
I than tired to find a link to collect from but I only found the mac version :
`https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl`

**Comment by eppoj** [comment]
I'm using an nvidia jetson nano. So I installed it with 
` sudo pip3 install   https://developer.download.nvidia.com/compute/redist/jp/v42/tensorflow-gpu/tensorflow_gpu-1.14.0+nv19.7-cp36-cp36m-linux_aarch64.whl`
But this might not be usefull for you

**Comment by AwesomeLele** [comment]
Nope, it doesn't work for linux but thanks anyway. I'm trying to find a wheel suitable for linux, I'll post it here in case I find it.

**Comment by AwesomeLele** [comment]
I found a working tf wheel here: https://github.com/yaroslavvb/tensorflow-community-wheels/issues/132. At the end of the topic there's a link:
https://github.com/vitalfadeev/tensorflow-1.14-noAVX-noCUDA-CPUonly-linux/raw/master/tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl.
I Had to downgrade to python 3.6 to install it otherwise it gives an error.
