### ISSUE TITLE
Why on DAVIS 2016, the model i trained performs much worse than the trained model you provided on your project web page? 

### ISSUE THREAD

**Issue by RuiFeiHe** [antonilo/unsupervised_detection#2]
Why on DAVIS 2016, the model i trained performs much worse than the trained model you provided on your project web page?

After training for 40 epochs, my test result on DAVIS 2016 is :
"The Average over the dataset: IoU is 0.49253097810762825 and MAE is 0.13433317588858826
The Average over sequences IoU is 0.4999786164052608"

And the test result of the davis_best_model you offered, using my device, is : 
"The Average over the dataset: IoU is 0.598809920117678 and MAE is 0.06665062332569166
The Average over sequences IoU is 0.597369491694537"

I wonder what caused the difference.
Is it because you trained for more epochs or other reasons?

Hoping for your reply.

**Comment by antonilo** [comment]
Hi @RuiFeiHe, thanks for your interest in our project!
You could for sure improve the results training longer. It is also possible to get slightly difference in performance for each run, but differences should be small. Did you reported the best score or just the last one?

**Comment by RuiFeiHe** [comment]
Hello, @antonilo ,thanks for your quick reply！

I did use the best model for testing. 
Considering of the training epoch factor, this time, I ran two identical experiments, each trained for 200 epochs. 
And I get the following results:
"The Average over the dataset: IoU is 0.5370813250873963 and MAE is 0.11571520393670992
The Average over sequences IoU is 0.5401700757"
"The Average over the dataset: IoU is 0.5221546808647927 and MAE is 0.07263825114729792
The Average over sequences IoU is 0.5348582947857214"

It seems that there still exist noticeable difference between my trained model and your best model.
Do you have any clues for that？

**Comment by antonilo** [comment]
hi @RuiFeiHe, could you make sure that the flag `train_partition='trainval'`? 
Did you change any hyperparameter? 
If not, could you repeat the experiment and report results?

**Comment by RuiFeiHe** [comment]
hello, @antonilo , when I first downloaded your files, it seems that the default value of `train_partition` is 'train'.
After I set it to 'trainval' , the result I get is very close to yours.
Thanks.

**Comment by fyangneil** [comment]
@RuiFeiHe Hi, Have you reproduced the number on three datasets reported in paper?
