### ISSUE TITLE
error when running post_processing.py

### ISSUE THREAD

**Issue by fyangneil** [antonilo/unsupervised_detection#6]
ImportError: /home/BaseCode/MovingObjectDetetection/unsupervised_detection/post_processing/pyflow.so: undefined symbol: _Py_ZeroStruct

**Comment by jinwchoi** [comment]
Hi @fyangneil, how did you resolve this issue?

**Comment by fyangneil** [comment]
I have no idea.
________________________________

**Comment by jinwchoi** [comment]
It seems that you need to setup this: https://github.com/pathak22/pyflow

**Comment by fyangneil** [comment]
i build it myself.
But do not get the number reported in paper.
________________________________

**Comment by fyangneil** [comment]
Do you get the number reported in paper?
________________________________
